function ExportFile01 = tmpimportmasks(filename, dataLines)
%IMPORTFILE Import data from a text file
%  EXPORTFILE01 = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the numeric data.
%
%  EXPORTFILE01 = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  ExportFile01 = importfile("X:\121250_PolyKARD\5-Data\02_Raman\2020.10_Fraunhofer\Raw Data\MATLAB export\Masks\Export File 01", [15, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 16-Nov-2020 15:48:01

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [15, Inf];
end

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 32);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["ExportedASCIIFile", "VarName2", "VarName3", "VarName4", "VarName5", "VarName6", "VarName7", "VarName8", "VarName9", "VarName10", "VarName11", "VarName12", "VarName13", "VarName14", "VarName15", "VarName16", "VarName17", "VarName18", "VarName19", "VarName20", "VarName21", "VarName22", "VarName23", "VarName24", "VarName25", "VarName26", "VarName27", "VarName28", "VarName29", "VarName30", "VarName31", "VarName32"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
ExportFile01 = readtable(filename, opts);

%% Convert to output type
ExportFile01 = table2array(ExportFile01);
end